# Generated by Django 5.1.6 on 2025-04-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_autctionlistings_bids_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutctionListings',
            new_name='AuctionListings',
        ),
    ]
